{% set name = "napari-proofread-brainbow" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-proofread-brainbow-{{ version }}.tar.gz
  sha256: 63cec564573320fcbc6b5ec205a59f4a95bfbf2448942329eb5c7c5f99bd554d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8,<3.11
    - qtpy

test:
  imports:
    - napari_proofread_brainbow
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-proofread-brainbow/
  summary: proofreading Brainbow images with napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
