{% set name = "napari-proofread-brainbow" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6c1e4317371e68595a13db675c7e05835b10aab750685a3f0fae9af685916c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_proofread_brainbow
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-proofread-brainbow/
  summary: proofreading Brainbow images with napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
